safe: false

# build settings
markdown: kramdown
highlighter: rouge
lsi: false
permalink: /:title

title: "Bonne année !"
description: "Retours sur l'année passée pour vous souhaiter une belle année future"
baseurl: "/onepage"
url: "https://bonneannee.6x8.org" # replace by your site's url
twitter_username: zemoko
github_username:  zemoko
accent: "#f7f7e6" # accent color for blog column

author: "Your Name"
address: "Your Street, <br>Your City, Country"
email: "your@email.com"

# google analytics tracking code, please change the value
g_analytics: ""

# language settings
isolang: fr

# exclude files
exclude:
  - LICENSE
  - README.md
